/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.HashTable;
import EDD.MonticuloBinario;
import EDD.NodoDocumento;
import EDD.NodoUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author jonathanpizzurro
 */
public class VentanaImpresora extends javax.swing.JFrame {

    /**
     * Creates new form VentanaImpresora
     */
    public static HashTable table;
    public static MonticuloBinario montBinario;

    public VentanaImpresora(HashTable hash,MonticuloBinario montBinario) {
        initComponents();
        this.table = hash;
        this.montBinario = montBinario;
                this.colaDoc.setText(montBinario.imprimirMonticulo(""));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonImprimir = new javax.swing.JButton();
        BotonCancelarImpresion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tituloDocumento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        colaDoc = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Impresora");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        BotonImprimir.setText("Imprimir");
        BotonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, -1));

        BotonCancelarImpresion.setText("Cancelar impresion");
        BotonCancelarImpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarImpresionActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCancelarImpresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Titulo Documento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        getContentPane().add(tituloDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, -1));

        colaDoc.setColumns(20);
        colaDoc.setRows(5);
        jScrollPane1.setViewportView(colaDoc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 280, 260));

        jButton1.setText("<--");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCancelarImpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarImpresionActionPerformed
        // TODO add your handling code here:

        String usuario = this.Usuario.getText();
        int indice = table.BuscarUser(usuario);
        NodoUsuario user = table.usuarios[indice];
        if (user != null) {
            NodoDocumento doc = user.buscarDoc(tituloDocumento.getText());
            if (doc != null) {
                doc.setEtiquetaDeTiempo(0);
                for (int i = 0; i < this.montBinario.tamaño; i++) {
                    if (this.montBinario.monticulo[i] != null) {
                        this.montBinario.reorganizarHaciaAbajo();
                    }
                    
                }
                JOptionPane.showMessageDialog(rootPane, this.montBinario.extraerMinimo().titulo);
            }
        }
        this.colaDoc.setText(montBinario.imprimirMonticulo(""));


    }//GEN-LAST:event_BotonCancelarImpresionActionPerformed

    private void BotonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonImprimirActionPerformed
        // TODO add your handling code here:

        String usuario = Usuario.getText();
        int indice = table.BuscarUser(usuario);
        NodoUsuario nodo = table.usuarios[indice];
        if (nodo != null) {
            NodoDocumento nd = nodo.buscarDoc(tituloDocumento.getText());
            if (nd != null) {
                montBinario.insertar(nd);
                JOptionPane.showMessageDialog(rootPane, "DOCUMENTO AGREGADO", usuario, HEIGHT);
                this.colaDoc.setText(montBinario.imprimirMonticulo(""));
            }
        }

    }//GEN-LAST:event_BotonImprimirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaPrincipal ventPrincipal = new VentanaPrincipal(table,montBinario);
        ventPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaImpresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaImpresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaImpresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaImpresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaImpresora(table,montBinario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCancelarImpresion;
    private javax.swing.JButton BotonImprimir;
    private javax.swing.JTextField Usuario;
    private javax.swing.JTextArea colaDoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tituloDocumento;
    // End of variables declaration//GEN-END:variables
}
