/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.HashTable;
import EDD.MonticuloBinario;
import EDD.NodoDocumento;

/**
 *
 * @author jonathanpizzurro
 */
public class VentanaDocumento extends javax.swing.JFrame {
    public static MonticuloBinario montBinario;
    public static HashTable table;
    

    /**
     * Creates new form Ventana3
     * @param hash
     * @param montBinario
     */
    public VentanaDocumento(HashTable hash, MonticuloBinario montBinario) {
        initComponents();
        this.table = hash;
        this.montBinario = montBinario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        textTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textTamano = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textDocumento = new javax.swing.JTextField();
        mostrarCola = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDocumentos = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        AgregarDocumento = new javax.swing.JButton();
        eliminarDocumento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Documentos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 6, -1, -1));

        label.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        label.setText("Titulo");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 105, -1, -1));

        textTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTituloActionPerformed(evt);
            }
        });
        getContentPane().add(textTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 129, 111, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Tamaño");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 170, -1, -1));
        getContentPane().add(textTamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 202, 111, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("Tipo Documento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, -1));
        getContentPane().add(textDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 273, 111, -1));

        mostrarCola.setText("Mostrar cola");
        mostrarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarColaActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 320, 111, -1));

        textAreaDocumentos.setColumns(20);
        textAreaDocumentos.setRows(5);
        jScrollPane1.setViewportView(textAreaDocumentos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 79, 332, 161));

        jButton1.setText("<--");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 50, -1));

        AgregarDocumento.setText("Agregar Documento");
        AgregarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 284, -1, -1));

        eliminarDocumento.setText("Eliminar Documento");
        eliminarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 284, -1, -1));

        jLabel4.setText("Usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 47, -1, -1));
        getContentPane().add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, 111, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTituloActionPerformed

    private void mostrarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarColaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaPrincipal ventPrincipal = new VentanaPrincipal(table,montBinario);
        ventPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AgregarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDocumentoActionPerformed
        String usuario = textUsuario.getText();
        String titulo = textTitulo.getText();
        String tamano = textTamano.getText();
        String documento = textDocumento.getText();
        
        String texto = "Usuario: " + usuario + "\nTítulo: " + titulo + "\nTamaño: " + tamano + "\nTipo: " + documento;
        textAreaDocumentos.setText(texto);
        this.table.insertarDocumento(usuario,titulo,tamano,documento,0);
        this.table.imprimir();
    }//GEN-LAST:event_AgregarDocumentoActionPerformed

    private void eliminarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarDocumentoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_eliminarDocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDocumento(table,montBinario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarDocumento;
    private javax.swing.JButton eliminarDocumento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JButton mostrarCola;
    private javax.swing.JTextArea textAreaDocumentos;
    private javax.swing.JTextField textDocumento;
    private javax.swing.JTextField textTamano;
    private javax.swing.JTextField textTitulo;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
